### ISSUE TITLE
A couple codel-ly notes

### ISSUE THREAD

**Issue by dtaht** [althea-mesh/althea-firmware#55]
@jkilpatr I just wanted to comment on your recent blog ( https://medium.com/althea-mesh/althea-development-update-62-free-tier-design-and-the-life-of-a-packet-f49f87fdc203 ) 

1) One thought was that you could use sch_cake rather than htb for your "free" tier and for nat awareness. It's been in openwrt a long time. Paper and discussion here while we mainlined it: https://lwn.net/Articles/758353/

2) "The codel operator on the router side doesn’t actually serve any useful purpose as it’s can’t identify connections because of the encryption."

Um, that's not how I would put it. The fq part puts each vpn connection into its own flow, the codel part attempts to keep queue lengths short by shooting at packets in each "vpn flow" until it is under control. So the codel bit is important to keeping overall queue lengths short, but is suboptimal without having insight into the unencrypted.

I keep hoping fq_codel *in* wireguard will appear, that would do the work before it gets encrypted, or after it emerges from the tunnel. But you can put things like cake on wg0, I think.

3) Over ethernet up/downlinks I'd suggest a classifer that puts your "free" traffic into the cake "background" queue.

But: My understanding of your design thus far seems to indicate you are doing this over wifi, which has it's own fq_codel stack on the ath9k, mt76, and ath10k, and wifi can be wildly variable, and thus rate limiting is either too much or too little. Instead I'd suggest you implement weighted fair queuing in front of the wifi with no rate limiter and let the wifi stack push back naturally, using weighted drr to give you your tiers - at least on those chipsets.

4) Have you any thought towards getting the new babel tlvs into the mainline protocol? There's been a bunch of major mods and bug fixes landing of late.

**Comment by jkilpatr** [comment]
@dtaht  first all I gotta apologize for leaving this here for 5 months, I had my github notification email set to an address I didn't check often when you submitted this. :( 


> Um, that's not how I would put it. The fq part puts each vpn connection into its own flow, the codel part attempts to keep queue lengths short by shooting at packets in each "vpn flow" until it is under control. So the codel bit is important to keeping overall queue lengths short, but is suboptimal without having insight into the unencrypted.

So we have a peer to peer layer of encryption as well as an end to end layer, I had cake applied after the peer to peer level so no matter how many streams there where they would all appear to be the same to cake. I had intended to put it on top of the peer to peer layer so that it could do exactly the task you describe. 

> One thought was that you could use sch_cake rather than htb for your "free" tier and for nat awareness. It's been in openwrt a long time. Paper and discussion here while we mainlined it: https://lwn.net/Articles/758353/

Can I reliably use cake to limit bandwidth? 

> If a given queue does not use all of its allocation, that bandwidth is naturally made available to the other classes of service. 
 
My reading of the documentation would turn up lines like this that make me believe otherwise. 

> Over ethernet up/downlinks I'd suggest a classifer that puts your "free" traffic into the cake "background" queue.

This gets into interaction with Babel actually. We've wanted to offer a higher speed versus a lower cost ability for route selection for a while, but we need a way to distinguish this lower priority traffic and generate lower priority routes across the network. Otherwise we end up having trouble communicating 'x is using background bandwidth and should thus be charged less / nothing at all'. 

The free tier as it is is simply a constant discount for everyone that you may or may not take advantage of. It's dangerous to not heavily restrict this as we wouldn't be able to figure out what was 'free tier' or 'regular' traffic once it got a few hops away. 

> But: My understanding of your design thus far seems to indicate you are doing this over wifi, which has it's own fq_codel stack on the ath9k, mt76, and ath10k, and wifi can be wildly variable, and thus rate limiting is either too much or too little. Instead I'd suggest you implement weighted fair queuing in front of the wifi with no rate limiter and let the wifi stack push back naturally, using weighted drr to give you your tiers - at least on those chipsets.

We're doing this over point to point commercial wireless gear. So it's not running 802.11 and is designed for backhaul usage. That being said throughput can still vary more than a wired connection ever would. The real problem is that these point to point antennas present 'packet loss' as very high latency thanks to transparent retires.

**Comment by dtaht** [comment]
There doesn't seem to be much I can respond to directly above, except: On wired links you can certainly rely on cake doing bandwidth allocation (and framing) right. I have been stressing that people need to get framing correct of late, since so many have been getting it wrong on dsl and cable modems and not getting correct results.

 I am no fan of commercial wireless gear and hope you give reflashed with openwrt and ath9k/ath10k gear a shot instead.

**Comment by jkilpatr** [comment]
> There doesn't seem to be much I can respond to directly above, except: On wired links you can certainly rely on cake doing bandwidth allocation (and framing) right. I have been stressing that people need to get framing correct of late, since so many have been getting it wrong on dsl and cable modems and not getting correct results.

Is there a blog post or other documentation where I can read about this? We got some really great perf improvements recently by tuning the HTB quantum correctly so I'm eager to try and fix other things I may have tuned wrong out of the gate. 

> I am no fan of commercial wireless gear and hope you give reflashed with openwrt and ath9k/ath10k gear a shot instead.

There's a version of the Ubnt firmware where ping6 ff02::1 will cause the radios to freeze and drop all packets for half a second. But for the time being we're trying to keep things moving quickly, so reflashing radios and routers isn't on the table.

**Comment by dtaht** [comment]
We are actually working on a video about framing currently, I am not sure how to invite you into the slack channel, please drop me an email to dave.taht@gmail.com and I can do that. Getting the framing right is very important on DSL and cable, less so on fiber.

I tend to use the sqm-scripts to manage this stuff, which does make that tunable, and cake is pretty good, as I've mentioned.
